import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  FaCashRegister,
  FaMoneyBillWave,
  FaUndo,
  FaChartLine,
  FaBoxes,
  FaPrint,
} from "react-icons/fa";
import { useQuery } from "@tanstack/react-query";
import api from "@/lib/api";
import { SpinnerCustom } from "../loaders/Spinner";
import jsPDF from "jspdf";

interface DailySummaryResponse {
  sales: {
    count: number;
    grossSales: number;
    cashReceived: number;
    outstandingBalance: number;
  };
  payments: {
    cash: number;
    mobile: number;
    bank: number;
  };
  returns: {
    count: number;
    amount: number;
  };
  inventory: {
    lostQty: number;
  };
  profit: {
    netProfit: number;
    cogs: number;
  };
}

const StatCard = ({ title, value, icon, footer }: any) => (
  <Card className="rounded-2xl shadow-sm">
    <CardHeader className="flex flex-row items-center justify-between pb-2">
      <CardTitle className="text-sm font-medium text-muted-foreground">
        {title}
      </CardTitle>
      <div className="text-xl text-muted-foreground">{icon}</div>
    </CardHeader>
    <CardContent>
      <div className="text-2xl font-bold">{value}</div>
      {footer && <p className="text-xs text-muted-foreground mt-1">{footer}</p>}
    </CardContent>
  </Card>
);

export default function DailySummaryDashboard() {
  const { data, isLoading } = useQuery({
    queryKey: ["daily"],
    queryFn: async () => {
      const res = await api.get<DailySummaryResponse>(
        `/api/dashboard/daily-summary`
      );
      return (res as any).data;
    },
    refetchOnWindowFocus: false,
  });

  const exportPdf = () => {
  if (!data) return;

  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text("End of Day Summary", 14, 20);

  doc.setFontSize(11);

  let y = 35;

  const col1 = 14;
  const col2 = 120;
  const rowHeight = 8;

  const drawRow = (label: string, value: string, bold = false) => {
    if (bold) doc.setFont("helvetica", "bold");
    doc.text(label, col1, y);
    doc.text(value, col2, y, { align: "right" });
    doc.setFont("helvetica", "normal");
    y += rowHeight;
  };

  const drawSection = (title: string) => {
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.text(title, col1, y);
    doc.setFont("helvetica", "normal");
    y += rowHeight;
  };

  /* ================= SALES ================= */
  drawSection("Sales Summary");
  drawRow("Total Sales", `${data.sales.count}`);
  drawRow("Gross Revenue", `${data.sales.grossSales.toFixed(2)}`);
  drawRow("Cash Received", `${data.sales.cashReceived.toFixed(2)}`);
  drawRow(
    "Outstanding Balance",
    `${data.sales.outstandingBalance.toFixed(2)}`
  );

  /* ================= PAYMENTS ================= */
  drawSection("Payment Breakdown");
  drawRow("Cash Payments", `${data.payments.cash.toFixed(2)}`);
  drawRow("MoMo Payments", `${data.payments.momo.toFixed(2)}`);
  drawRow("Bank Payments", `${data.payments.bank.toFixed(2)}`);

  /* ================= RETURNS & PROFIT ================= */
  drawSection("Returns & Profit");
  drawRow("Returns", `${data.returns.amount.toFixed(2)}`);
  drawRow("COGS", `${data.profit.cogs.toFixed(2)}`);
  drawRow(
    "Net Profit",
    `${data.profit.netProfit.toFixed(2)}`,
    true
  );

  /* ================= FOOTER ================= */
  y += 10;
  doc.setFontSize(9);
  doc.text("Generated by TentHub POS", col1, y);
  doc.text(
    new Date().toLocaleString(),
    col2,
    y,
    { align: "right" }
  );

  doc.save("daily-summary.pdf");
};

  if (isLoading) return <SpinnerCustom />;

  return (
    <div className="space-y-6 py-10 px-5">
      <div className="flex justify-between items-center">
        <h2 className="text-lg font-semibold">Daily Summary</h2>
        <button
          onClick={exportPdf}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary text-primary-foreground text-sm"
        >
          <FaPrint /> Export PDF
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title="Total Sales"
          value={`${data?.sales.count} sales`}
          icon={<FaCashRegister />}
          footer={`Outstanding: ₵${data?.sales.outstandingBalance.toFixed(2)}`}
        />

        <StatCard
          title="Gross Revenue"
          value={`₵${data?.sales.grossSales.toFixed(2)}`}
          icon={<FaMoneyBillWave />}
          footer={`Cash received: ₵${data?.sales.cashReceived.toFixed(2)}`}
        />

        <StatCard
          title="Returns"
          value={`₵${data?.returns.amount.toFixed(2)}`}
          icon={<FaUndo />}
          footer={`${data?.returns.count} return(s)`}
        />

        <StatCard
          title="Net Profit"
          value={`₵${data?.profit.netProfit.toFixed(2)}`}
          icon={<FaChartLine />}
          footer={`COGS: ₵${data?.profit.cogs.toFixed(2)}`}
        />
      </div>

      {/* Payment Breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <StatCard
          title="Cash Payments"
          value={`₵${data?.payments.cash.toFixed(2)}`}
          icon={<FaMoneyBillWave />}
        />
        <StatCard
          title="MoMo Payments"
          value={`₵${data?.payments.momo.toFixed(2)}`}
          icon={<FaMoneyBillWave />}
        />
        <StatCard
          title="Bank Payments"
          value={`₵${data?.payments.bank.toFixed(2)}`}
          icon={<FaMoneyBillWave />}
        />
      </div>

      <Card className="rounded-2xl">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <FaBoxes /> Inventory Impact Today
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between">
            <span className="text-sm text-muted-foreground">
              Lost / Damaged Items
            </span>
            <span className="text-lg font-semibold">
              {data?.inventory.lostQty}
            </span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
